# paymentservice deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice-deploy
  labels:
    app: paymentservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paymentservice
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      imagePullSecrets:
      - name: nexus-registry-secret
      containers:
        - name: paymentservice
          image: 192.168.1.16:8082/paymentservice:1.0.9
          ports:
          - containerPort: 50051
          env:
          - name: PORT
            value: "50051"
          - name: DISABLE_PROFILER
            value: "1"
---
# paymentservice service

apiVersion: v1
kind: Service
metadata:
  name: paymentservice
  labels:
    app: paymentservice
spec:
  selector:
      app: paymentservice
  type: ClusterIP
  ports:
    - port : 50051
      targetPort: 50051