# redis deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deploy
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      imagePullSecrets:
      - name: nexus-registry-secret
      containers:
        - name: redis
          image: redis:alpine
          ports:
          - containerPort: 6379
          env:
          - name: PORT
            value: "6379"
          volumeMounts:
            - name:  redis-data
              mountPath:  /data
      volumes:
        - name:  redis-data
          emptyDir: {} # ephemeral volume
---
# redis service

apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec:
  selector:
      app: redis
  type: ClusterIP
  ports:
    - port : 6379
      targetPort: 6379