# shippingservice deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: shippingservice-deploy
  labels:
    app: shippingservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shippingservice
  template:
    metadata:
      labels:
        app: shippingservice
    spec:
      imagePullSecrets:
      - name: nexus-registry-secret
      containers:
        - name: shippingservice
          image: 192.168.1.16:8082/shippingservice:1.0.2
          ports:
          - containerPort: 50051
          env:
          - name: PORT
            value: "50051"
---
# shippingservice service

apiVersion: v1
kind: Service
metadata:
  name: shippingservice
  labels:
    app: shippingservice
spec:
  selector:
      app: shippingservice
  type: ClusterIP
  ports:
    - port : 50051
      targetPort: 50051